### ISSUE TITLE
Make flavour list directly editable.

### ISSUE THREAD

**Issue by halestorm962** [McGillEUS/frostbite-tubtracker#5]
Remove flavour info section, make the flavour list contain all flavour info. Instead of the separate add/edit flavour section, make the list editable in-place when the edit button is clicked. Also add an open/close tub button to the end of each row. See Rules.JSON manager for inspiration.

**Comment by alexanderhale** [comment]
Accomplished in barebones. Could be improved by saving changes automatically instead of clicking "Save Changes" each time (that's now issue #22)
